(deftemplate credit-card-payment
  (slot action_type)
  (slot transaction_id)
  (slot email)
  (slot email_domain)
  (slot user_fullname)
  (slot user_name)
  (slot user_id)
  (slot user_created)
  (slot user_country)
  (slot user_city)
  (slot user_region)
  (slot user_zip)
  (slot user_street)
  (slot user_street2)
  (slot payment_method)
  (slot card_fullname)
  (slot card_bin)
  (slot card_hash)
  (slot card_last)
  (slot card_expire)
  (slot avs_result)
  (slot cvv_result)
  (slot status_3d)
  (slot bank)
  (slot phone_number)
  (slot transaction_type)
  (slot transaction_amount (type INTEGER))
  (slot transaction_currency)
  (slot brand_id)
  (slot shipping_city)
  (slot shipping_region)
  (slot shipping_zip)
  (slot shipping_street)
  (slot shipping_street2)
  (slot shipping_phone)
  (slot shipping_fullname)
  (slot shipping_method)
  (slot billing_country)
  (slot billing_city)
  (slot billing_region)
  (slot billing_zip)
  (slot billing_street)
  (slot billing_street2)
  (slot billing_phone)
  (slot discount_code)
  (slot gift)
  (slot gift_message)
  (slot merchant_id)
  (slot merchant_category)
  (multislot items_names)
  (multislot items_quantities)
  (multislot items_prices)
  (multislot items_categories)
  (multislot items_skus)
)

(deftemplate credit-card-payment-response
  (slot transaction_id)
  (slot activation_rule (type STRING))
  (slot action)
)

(deftemplate bank-to-provider
  (slot bank)
  (slot provider)
)