from typing import Optional, List

from pydantic import BaseModel


class CreditCardPaymentRequestModel(BaseModel):
    action_type: Optional[str]
    transaction_id: Optional[str]
    email: Optional[str]
    email_domain: Optional[str]
    user_fullname: Optional[str]
    user_name: Optional[str]
    user_id: Optional[str]
    user_created: Optional[str]
    user_country: Optional[str]
    user_city: Optional[str]
    user_region: Optional[str]
    user_zip: Optional[str]
    user_street: Optional[str]
    user_street2: Optional[str]
    payment_method: Optional[str]
    card_fullname: Optional[str]
    card_bin: Optional[str]
    card_expire: Optional[str]
    avs_result: Optional[str]
    cvv_result: Optional[str]
    status_3d: Optional[str]
    bank: Optional[str]
    phone_number: Optional[str]
    transaction_type: Optional[str]
    transaction_amount: Optional[int]
    transaction_currency: Optional[str]
    brand_id: Optional[str]
    shipping_city: Optional[str]
    shipping_region: Optional[str]
    shipping_zip: Optional[str]
    shipping_street: Optional[str]
    shipping_street2: Optional[str]
    shipping_phone: Optional[str]
    shipping_fullname: Optional[str]
    shipping_method: Optional[str]
    billing_country: Optional[str]
    billing_city: Optional[str]
    billing_region: Optional[str]
    billing_zip: Optional[str]
    billing_street: Optional[str]
    billing_street2: Optional[str]
    billing_phone: Optional[str]
    discount_code: Optional[str]
    merchant_id: Optional[str]
    merchant_category: Optional[str]
    items_names: List[str] = []
    items_quantities: List[str] = []
    items_prices: List[str] = []
    items_categories: List[str] = []
    items_skus: List[str] = []
